version: '3.11'

services:
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminqwerty
      POSTGRES_DB: content_api
    ports:
      - "5432:5432"

#  api:
#    build: .
#    ports:
#      - "8000:8000"
#    depends_on:
#      redis:
#        condition: service_started
#        restart: true