version: '3.11'

services:
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
    ports:
      - "6380:6379"


  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
        restart: true